CREATE TABLE [minenet].[TagHistory]
(
	--[HistoryTagId]                                  INT                         IDENTITY(1,1),
  [TagId]                                         INT                         NULL,
  [Address]                                       INT                         NULL,
  [ZoneNumber]                                    INT                         NULL,
  [DateKey]                                       DATETIME                    NULL,
  [MinuteKey]                                     INT                         NULL,
  [LastName]                                      VARCHAR(26)                 NULL,
  [FirstName]                                     VARCHAR(26)                 NULL,
  [Zone]                                          VARCHAR(50)                 NULL,
  [Reported]                                      DATETIME                    NULL,
  [Battery]                                       INT                         NULL,
  [SignalStrength]                                INT                         NULL,
  [Message]                                       INT                         NULL,
  [Temperature]                                   INT                         NULL,
  [Source]                                        INT                         NULL,
  [LastZone]                                      VARCHAR(50)                 NULL,
  [LastReported]                                  DATETIME                    NULL,
  [RateReported]                                  INT                         NULL,
  [LastRate]                                      INT                         NULL,
  [MessageCount]                                  INT                         NULL,
  [MessageAlarm]                                  INT                         NULL,
  [MinerID]                                       FLOAT                       NULL,

  --CONSTRAINT [PK_HistoryTag_HistoryTagId]         PRIMARY KEY CLUSTERED       ([HistoryTagId] ASC),
)
