// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MvcWeb.Models;

[Keyless]
[Table("TagHistory", Schema = "minenet")]
public partial class TagHistory
{
    public int? TagId { get; set; }

    public int? Address { get; set; }

    public int? ZoneNumber { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateKey { get; set; }

    public int? MinuteKey { get; set; }

    [StringLength(26)]
    [Unicode(false)]
    public string? LastName { get; set; }

    [StringLength(26)]
    [Unicode(false)]
    public string? FirstName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? Zone { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Reported { get; set; }

    public int? Battery { get; set; }

    public int? SignalStrength { get; set; }

    public int? Message { get; set; }

    public int? Temperature { get; set; }

    public int? Source { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? LastZone { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastReported { get; set; }

    public int? RateReported { get; set; }

    public int? LastRate { get; set; }

    public int? MessageCount { get; set; }

    public int? MessageAlarm { get; set; }

    [Column("MinerID")]
    public double? MinerId { get; set; }
}