// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

using Microsoft.EntityFrameworkCore;

namespace MvcWeb.Models;

public partial class MineNetDBContext : DbContext {

  public virtual DbSet<TagHistory> TagHistories { get; set; }

  public MineNetDBContext(DbContextOptions<MineNetDBContext> options) : base(options) { }

  protected override void OnModelCreating(ModelBuilder modelBuilder) => OnModelCreatingPartial(modelBuilder);
  partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
